### ISSUE TITLE
Domain Error

### ISSUE THREAD

**Issue by mlandgraf13** [JuliaAstrodynamics/Astrodynamics.jl#1]
Howdy, looks like there is a problem in the elements conversion. I get:

rv=[2672.9215894693
-5852.513642806324
-1705.019290659769
    7.58861779126684
5.161409874365992
    -5.820134371321003];

elements(rv,planets["earth"]["mu"])
DomainError
at In[4]:1
 in elements at .../Astrodynamics.jl/src/frames.jl:23

Can you try to reproduce the error?

**Comment by helgee** [comment]
Well, that took some time. But the problem seems to have gone away on the current Julia development version.

**Comment by mlandgraf13** [comment]
Thanks, Helge.
