### ISSUE TITLE
Conflicting Requirements between Julia 0.5.1 and AStdynamics packages

### ISSUE THREAD

**Issue by OrbitalMechanic** [JuliaAstrodynamics/Astrodynamics.jl#2]
I've updated to Julia 0.5.1 on a Mac Pro (desktop machine) running Mac OS X ver. 10.12.4. Running Pkg.update() produces the messages in the attached file.

Any suggestions?

Sam Dupree.

[Messages_from_Julia_update.txt](https://github.com/JuliaAstrodynamics/Astrodynamics.jl/files/948801/Messages_from_Julia_update.txt)

**Comment by helgee** [comment]
Hi Sam,
this is expected. I decided to target Julia 0.6 with the reorganized packages because the new type system greatly simplifies the code in many cases. I assume that 0.6 will be released very soon.

**Comment by helgee** [comment]
Since 0.6 is officially out, I am closing this.
